# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Bruno Paniagua Jimenez
title: Product Sustainer Specialist 
email: Bruno.pj27@gmail.com
# email_title: Email (Email title override)
phone: 591 74269564 
# phone_title: Phone (Phone title override)
website: https://bruda27.github.io/BrunoPaniagua/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: False

# Social links
twitter_username: BrunoPj27
github_username: Bruda27
stackoverflow_username: "7090044"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: bruno-paniagua-jimenez-899a67139
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
  #icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  #url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Bruno.png
about_content: | # this will include new lines to allow paragraphs
 Results-driven Analyst and Developer with a proven track record in business development, project management, and IT administration. Demonstrated expertise in handling inside information, 
 meticulous migrations planning, effective audit management, and successful execution of marketing campaigns,showcasing adaptability and technical acumen.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
        # other value (or no value) means no border will be displayed
        title: Profesional life cylcle Codification
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #ink_text: Link Text
        #additional_links:
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - #title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Projects are defined and managed in my Blog, check them out!
        description: | # this will include new lines to allow paragraphs
         Automation, AI and Machine learning.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Inovagreen
        sub_title: Sales Manager and Developer
        caption: feb. 2015 - may. 2016 -1 year & 4 months
        link: https://www.linkedin.com/company/innovagreen-technology/about/
              http://www.innovagreentec.com/
        quote: >
          Domotic Technology and Industrial Automation IOT devices.
        description: | # this will include new lines to allow paragraphs
          
          Spearheaded business development initiatives, including strategic asset planning and execution of marketing campaigns.
          Led meticulous migrations planning, zoning, and version capabilities within a scrum framework. Managed audit processes with precision, ensuring compliance and mitigating potential risks.
      - layout: right
        title: Convergys
        sub_title: Compliance Analyst Specialist Support Agent
        caption: sept. 2016 - dic. 2016 · 4 Months
        link: https://www.concentrix.com/
        quote: >
          Health care services, SIGNA DENTAL
        description: | # this will include new lines to allow paragraphs
          Specialized in delivering compliance and policy information for an insurance company, contributing to its regulatory adherence.
          Provided essential support for business development activities, ensuring alignment with compliance standards.

      - layout: right
        title: Microsoft Intune, Tek Experts 
        sub_title: Senior Product Support Specialist
        caption: may. 2017 - jun. 2018 · 1 year & 2 months
        link: https://careers.tek-experts.com/costarica
        quote: >
         https://learn.microsoft.com/en-us/mem/intune/fundamentals/what-is-intune
        description: | # this will include new lines to allow paragraphs
          Led as a Senior Product Support Specialist, responsible for designing infrastructure architecture for both existing clients and new customers using Microsoft Intune technology.
          Managed server administration for on-premises and cloud environments,Coordinated sprint deadline processes and facilitated user acceptance testing, ensuring seamless integration and client satisfaction.

      - layout: right
        title: SolveIT Solutions / clocky.app
        sub_title: IT Administrator
        caption: jun. 2018 - feb. 2019 · 9 Months
        link: https://clocky.app/
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Implemented comprehensive IT solutions for call centers and logistics companies, optimizing hardware and software inventory management.
          Contributed to business strategy, focusing on subscription-based models and recurring revenue strategies.
          Engaged in process and resource management, ensuring efficient business operations.

      - layout: right
        title: Eurofins IT
        sub_title: Senior Global Support Desktop Engineer
        caption: Apr 21th 2019 - May 25th 2020 1 year & 1 month
        link: https://www.eurofinsus.com/
        quote: >
          Eurofins Scientific is a group of international life sciences companies which provide a unique range of analytical testing services to clients across multiple industrie
        description: | # this will include new lines to allow paragraphs
          Managed global IT infrastructure, overseeing remote access troubleshooting and ensuring legal and compliance considerations.
          Successfully navigated complex incident report management and maintained robust communication channels with stakeholders.
         

      - layout: right
        title: Eurofins IT
        sub_title: Product Sustainer Specialist
        caption: Jun 1th 2020 - July 16th 2023 3 years y 1 month
        link: https://www.eurofinsus.com/food-testing/
        quote: >
         Eurofins is the leader in food, feed, and supplement testing, support, and development services
        description: | # this will include new lines to allow paragraphs
          Administered and developed the Eurofins Laboratory Management System (eLIMS), ensuring optimal functionality and user satisfaction.
          collaborative business alignment, sprint releases, engaging in version release discussions, software development updates, and Sprint User Acceptance Testing (UAT).
          Managed alert and monitoring systems, ensuring seamless operations within a decentralized network of laboratories.
    
                     
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Ministerio de Educacion Publica MEP Costa Rica (Public Education Ministery)
        sub_title: Senior High school diploma, technical degree on C++ oritened programing.
        caption: "2013-2017"
        quote: >
          Bachillerato en Educacion Media.
        #description: | # this will include new lines to allow paragraphs
          #Description of qualification
      - layout: top-right
        title: Universidad Americana, Laureate International Universities
        sub_title: Bachelor's Degree Juris Doctor Costa Rica.
        caption: 2013-2017
        quote: >
          Derecho Comercial (Coorporate Law)
        description: | # this will include new lines to allow paragraphs
          Economic decentralized model, Merger of commercial entities, Securities, Stock market contracts, Banking contracts, Unfair competition action.

      - layout: top-right
        title: Unviersidad Estatal a Distancia (UNED)
        sub_title: Systems Engineering
        caption: 2014-2020
        quote: >
          System node develpment
        description: | # this will include new lines to allow paragraphs
         system architecture, pattern design, and flow optimization, progaming and essential Networking.
      - layout: top-right
        title: Hacker Mentor
        sub_title: Ethical Hacking 
        caption: "2023"
        quote: >
          Cybersecurity,proactive identification and mitigation of security vulnerabilities. 
        description: | # this will include new lines to allow paragraphs
          controlled and authorized penetration testing to assess the security posture of systems, networks, and applications. Dedicated to ensuring the confidentiality, integrity, and availability of critical assets through the application of ethical hacking technique
          Exploits deployment, pasive & active target recognition,port and host scan,Enumeration,staged payloads, multihandler for reverse processes
      - layout: top-right
        #title: Institution name
        #sub_title: Qualifications (eg. BA Performing Arts)
        #caption: Date Range (eg. 2016 - 2019)
        quote: >
          <mark>TheInformation within this page follows The Apostille Convention, Hague Convention Abolishing the Requirement of Legalisation for Foreign Public Documents.
          DM-DVM-AC-DGEC-0544-2022
          DM-036-09-2017<mark>
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
